//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWPF.Model
{
    using GameWPF.Model.Enum;

    public partial class CharacterClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int BaseHealth { get; set; }
        public int BaseEndurance { get; set; }
        public int BaseDamage { get; set; }
        public string Image { get; set; }

        public CharacterClass() { }

        public CharacterClass(CharacterClassEnum characterClass)
        {
            Id = (int)characterClass;
            Name = characterClass.ToString();
            Description = characterClass.ToString();
            BaseHealth = characterClass.GetBaseHealth();
            BaseEndurance = characterClass.GetBaseEndurance();
            BaseDamage = characterClass.GetBaseDamage();
            Image = characterClass.GetImage();
        }

        public static implicit operator CharacterClassEnum(CharacterClass characterClass) => (CharacterClassEnum)characterClass.Id;

        public static explicit operator CharacterClass(CharacterClassEnum characterClass) => new CharacterClass(characterClass);
    }
}
