//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public int Experience { get; set; }
        public int Gold { get; set; }
        public int Health { get; set; }
        public int Endurance { get; set; }
        public int Damage { get; set; }
    
        public virtual CharacterClass Class { get; set; }
        public virtual User User { get; set; }
        public virtual Container Inventory { get; set; }
        public virtual ContainerItem Weapon { get; set; }
        public virtual ContainerItem Util { get; set; }
        public virtual ContainerItem Head { get; set; }
        public virtual ContainerItem Armor { get; set; }
    }
}
