//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerItem
    {
        public System.Guid Id { get; set; }
        public int Quantity { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual Item Item { get; set; }
    }
}
