//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWPF.Model
{
    using GameWPF.Model.Enum;

    public partial class ItemType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }

        public ItemType() { }

        public ItemType(ItemTypeEnum itemType)
        {
            Id = (int)itemType;
            Name = itemType.ToString();
            Image = itemType.GetImage();
        }

        public static implicit operator ItemTypeEnum(ItemType itemType) => (ItemTypeEnum)itemType.Id;

        public static explicit operator ItemType(ItemTypeEnum itemType) => new ItemType(itemType);
    }
}
