//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWPF.Model
{
    using GameWPF.Model.Enum;

    public partial class UserStatus
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public UserStatus() { }

        public UserStatus(UserStatusEnum userStatus)
        {
            Id = (int)userStatus;
            Name = userStatus.ToString();
        }

        public static implicit operator UserStatusEnum(UserStatus userStatus) => (UserStatusEnum)userStatus.Id;

        public static explicit operator UserStatus(UserStatusEnum userStatus) => new UserStatus(userStatus);
    }
}
