//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWPF.Model
{
    using GameWPF.Model.Enum;

    public partial class UserRole
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public UserRole() { }

        public UserRole(UserRoleEnum userRole)
        {
            Id = (int)userRole;
            Name = userRole.ToString();
        }

        public static implicit operator UserRoleEnum(UserRole userRole) => (UserRoleEnum)userRole.Id;

        public static explicit operator UserRole(UserRoleEnum userRole) => new UserRole(userRole);
    }
}
